### ISSUE TITLE
Introduce api protocol for listening connectors

### ISSUE THREAD

**Issue by richard-julien** [LuatixHQ/opencti#10046]
## Use case

The current OpenCTI implementation for listening connectors is based on AMQP.
User action -> API -> Push in Listen Queue <- Connector consuming
This is working fine but it force connector to run in an architecture that can directly connect the queuing system.
To have remote disconnected connectors this solution is no valid as nobody want to open a direct AMQP connection over internet.

> This new way of communication between this types of connectors and the platform will open more deployment types and so I hope more usage.

## Proposed Solution

We need to introduce a webhook based communication between the plateform and the connectors.

![Image](https://github.com/user-attachments/assets/ef0749ec-03db-47da-bedc-bca5b22558d4)

To prevent introduce a new piece in the stack, we decide to use the workers to execute the http post follow up

Introduce a new connector option: listen_protocol: "api" and other options

```
connector:
  listen_protocol: "api"
  listen_protocol_api_port: 7070
  listen_protocol_api_path: "/api/callback"
  listen_protocol_api_uri: "https://127.0.0.1:7070"
  listen_protocol_api_ssl: true
  listen_protocol_api_ssl_key: keypem
  listen_protocol_api_ssl_cert: certpem
```

## impacted connectors
- internal-enrichment
- internal-import-files

## worker impact
Worker will be responsible to consume the listen queue and do the http post to the connector.
For this we introduce some options on worker side to interact with the remote http api.

```
worker:
  listen_api_ssl_verify: false
  listen_api_http_proxy: "http://"
  listen_api_https_proxy: "https://"
```

## Additional Information

Linked to client python issue : https://github.com/OpenCTI-Platform/client-python/issues/850
