### ISSUE TITLE
How to Integrate OpenCTI with Elastic SIEM for IOC Enrichment and Event Correlation

### ISSUE THREAD

**Issue by CybDefender** [LuatixHQ/opencti#11276]
Priority : High
I’m currently working on integrating OpenCTI with Elastic SIEM. But when I look for documents, I get different guidance from OpenCTI and Elsatic(Providing both links below). I'm confused and stuck due to, which is the right way to integrate it exactly. I've applied the configurations, but yet not pulling data into SIEM. Anyone suggest the exact way to integrate the OpenCTI with Elastic SIEM?   😞 

Specifically, I’m looking to:

- Pull IOCs (e.g., IPs, domains, hashes) from OpenCTI.
- Ingest these into Elastic SIEM as enrichment data.
- Correlate them with logs/events ingested from various sources in the SIEM.
- Generate alerts when matches are found.

If anyone has experience with this setup or could point me toward best practices for enabling this integration, it would be greatly appreciated.

Thanks in advance for your support!

OpenCTI document link: https://github.com/OpenCTI-Platform/connectors/blob/master/stream/elastic/README.md
Elastic document link: https://www.elastic.co/docs/reference/integrations/ti_opencti

**Comment by alice-debra** [comment]
Hello @CybDefender,

For your use case, I recommend using the Elastic Stream Connector. This connector:
- Connects to OpenCTI's live stream
- Pushes IOCs (IPs, domains, hashes) in real-time to Elasticsearch
- Creates proper indices for threat intelligence data
- Is specifically designed for SIEM integration

Before starting the connector, you need to create a stream in OpenCTI:
- Go to Data > Data sharing > Live streams
- Click "Create stream"
- Configure filters to include the IOCs you want:
- Entity types: Indicator, Observable
- Observable types: IPv4-Addr, IPv6-Addr, Domain-Name, File (for hashes)
- Copy the Stream ID and use it in your connector configuration

And Configure Elasticsearch index templates.

You can also ask for help on our Slack: https://filigran-community.slack.com/. 

Please let me know if you need more help :)

Kind regards,

Alice

**Comment by CybDefender** [comment]
Hi Alice,

Happy for your response. :) 

Actually,

- I’ve successfully configured the Live Stream connection for Elastic.
- The connector configuration has been added to the docker-compose.yml file (see attached screenshots).

However, I’m currently stuck at the step “Configure Elasticsearch index templates.”
I’m unsure how to correctly set up the required index templates in Elasticsearch so that the streamed IOCs are stored and searchable properly.

I had also raised this issue in Slack (https://filigran-community.slack.com/archives/C06CF1N302W/p1749649133521189), but haven’t received any responses yet.

Would really appreciate if anyone could:

Share guidance or steps to configure the Elasticsearch index templates correctly.
Or point me to any reference material or working example for this integration.

Thanks in advance for your help!

![Image](https://github.com/user-attachments/assets/65e09f2b-09c1-4dd3-a147-8386224b9249)
![Image](https://github.com/user-attachments/assets/3d3753d4-ba1b-4d9b-9e82-9dcb43222899)

**Comment by alice-debra** [comment]
Hello again @CybDefender,

Can you try to include something like that in your connector configuration: 
```yml
    - ELASTICSEARCH_HOSTS=https://your-elasticsearch:9200
    - ELASTICSEARCH_APIKEY=your_api_key  # or username/password
    - CONNECTOR_JSON_CONFIG='{
        "output": {
          "include_labels": false
        },
        "setup": {
          "ilm": {
            "enabled": true,
            "policy_name": "opencti",
            "pattern": "000001",
            "overwrite": true
          },
          "template": {
            "enabled": true,
            "name": "opencti",
            "pattern": "opencti-*",
            "overwrite": true
          }
        }
      }'
```

Or do you prefer a more manual approach? 

Alice :)
