### ISSUE TITLE
Improve ingestion speed for massive reports

### ISSUE THREAD

**Issue by richard-julien** [LuatixHQ/opencti#1772]
## Use case

When platform ingest massive reports, all object_refs relations a created one by one. This behavior can lead to slow ingestion when massive reports are ingested.

In some condition if the ingestion is really too slow, rabbitmq can discard the message and restart again and again. See https://github.com/OpenCTI-Platform/opencti/issues/1441#issuecomment-865656252

## Current Workaround

No

## Proposed Solution

- Try to ingest object_refs with kind of batching systems.
- ???

**Comment by debelyoo** [comment]
I'm facing similar issues with my deployment. The problematic rabbitMQ messages are of size 12MB+ (up to 25MB). They are bundles containing a report with a ton of object_refs. I experience that with the MISP connector for instance.
I currently don't have a workaround for them.

**Comment by ckane** [comment]
I've been wanting to be able to sync mine against a MISP instance that's fully populated with all the available feeds.

My current process goes like this to populate MISP:

I go into the Sync Actions->List Feeds, and then "Load default feed metadata" which populates MISP with a whole bunch of publicly available threat feeds, Then I enable all the feeds, and enable caching of all of them, and then finally "Fetch and Store All Feed Data" to kick off the jobs to synchronize the feeds.

Once it is all populated, I've been connecting it to MISP by adding the following container to the `docker-compose.yml` in the example setup:
```yaml
  connector-misp:
    image: opencti/connector-misp:5.1.2
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_IMPORT_MISP_ID}
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=MISP
      - CONNECTOR_SCOPE=misp
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_LOG_LEVEL=info
      - MISP_URL=https://url.of.misp # Required
      - MISP_REFERENCE_URL= # Optional, will be used to create external reference to MISP event (default is "url")
      - MISP_KEY=<MY KEY FROM MISP GOES HERE> # Required
      - MISP_SSL_VERIFY=False # Required
      - MISP_DATETIME_ATTRIBUTE=timestamp # Required, filter to be used in query for new MISP events
      - MISP_CREATE_REPORTS=True # Required, create report for MISP event
      - MISP_CREATE_INDICATORS=True # Required, create indicators from attributes
      - MISP_CREATE_OBSERVABLES=True # Required, create observables from attributes
      - MISP_CREATE_OBJECT_OBSERVABLES=True # Required, create text observables for MISP objects
      - MISP_REPORT_CLASS=MISP Event # Optional, report_class if creating report for event
      - MISP_IMPORT_FROM_DATE=2000-01-01 # Optional, import all event from this date
      - MISP_IMPORT_DISTRIBUTION_LEVELS=0,1,2,3 # Optional, only import events with the given distribution levels
      - MISP_IMPORT_THREAT_LEVELS=1,2,3,4 # Optional only import events with the given threat levels
      - MISP_IMPORT_ONLY_PUBLISHED=True
      - MISP_IMPORT_WITH_ATTACHMENTS=True # Optional, try to import a PDF file from the attachment attribute
      - MISP_IMPORT_TO_IDS_NO_SCORE=40 # Optional, use as a score for the indicator/observable if the attribute to_ids is no
      - MISP_IMPORT_UNSUPPORTED_OBSERVABLES_AS_TEXT=False #  Optional, import unsupported observable as x_opencti_text
      - MISP_INTERVAL=5 # Required, in minutes
    restart: always
```

In particular, I've noticed that OpenCTI will end up spending an extremely long amount of time trying to ingest the "Operation SMN" report from Novetta, which is brought in via the CIRCL feed source.

My "workaround" is basically to have OpenCTI ignore the big reports, by setting `MISP_IMPORT_ONLY_PUBLISHED=True` and then sorting all of the events in MISP in descending order by # of attributes, and then un-publishing the bigger reports.
