### ISSUE TITLE
How to increase the number of connected workers?

### ISSUE THREAD

**Issue by AntoninHL** [LuatixHQ/opencti#1889]
Hello,

I don't really understand why the number of active workers remains fixed at one.
In my docker-compose.yml, I see these lines:

```
  worker:
    image: opencti/worker:5.1.4
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - WORKER_LOG_LEVEL=info
    depends_on:
      - opencti
    deploy:
      mode: replicated
      replicas: 3
    restart: always
```

I understood through this [post](https://github.com/OpenCTI-Platform/opencti/issues/1114) that we have to declare workers by ourselves, but I don't really know how.

Could you explain please?

Many thanks

A.

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }
