### ISSUE TITLE
Default Connector role not providing enough privilege

### ISSUE THREAD

**Issue by FocusedPanda** [LuatixHQ/opencti#2718]
## Description

Update 2023-01-17 - It appears that the default connector role does not provide enough privilege for some connectors to work properly.  Issues with connectors ingesting data can be worked around by setting up a new role containing the "Bypass all capabilities" privilege checked. This is not ideal.

I have setup the OpenCTI Datasets connector; I am able to see the Connector performing work in OpenCTI, as well as the sessions for the connector user. However, none of the sectors of geographies are being ingested into OpenCTI.

## Environment

1. OS: Debian 11 (bullseye)
2. OpenCTI version: 5.5.1
3. OpenCTI client:  Frontend
4. Other environment details:  All OpenCTI services are running in docker using Portainer; Elastic is in it's own Docker on a separate server.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an OpenCTI user for OpenCTI Datasets connector with 'Connector' role.
2. Add OpenCTI Datasets docker-compose details to existing configuration.
3. Modify configuration to use appropriate OpenCTI admin token, and random UUIDv4.
4. Start docker swarm and start dockers

## Expected Output

It is expected that the **Locations** -> **Regions**, **Countries**, and **Cities** sections in OpenCTI will be populated with data from https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/geography.json, and that **Entities** -> **Sectors** would be populated with data from https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/sectors.json.

## Actual Output

- The OpenCTI datasets connector successfully connects to the platform according to reviewing user sessions.
- Work is being done by the connector according to the Connector screen.
- No operations are being performed by the Connector.
- The only errors showing up in the OpenCTI interface are related to unicode characters used in the ANSSI entry.

## Additional information

When I checked the Elastic logs, I see the a log entry with the following error:

```
[{'name': 'ForbiddenAccess', 'message': 'You are not allowed to do this.'}, {'name': 'MissingReferenceError', 'message': 'Missing reference to handle creation'}, {'name': 'MissingReferenceError', 'message': 'Missing reference to handle creation'}, {'name': 'MissingReferenceError', 'message': 'Missing reference to handle creation'}, {'name': 'MissingReferenceError', 'message': 'Missing reference to handle creation'}, {'name': 'MissingReferenceError', 'message': 'Missing reference to handle creation'}, {'name': 'MissingReferenceError', 'message': 'Missing reference to handle creation'}, {'name': 'MissingReferenceError', 'message': 'Missing reference to handle creation'}, {'name': 'MissingReferenceError', 'message': 'Missing reference to handle creation'}, {'name': 'MissingReferenceError', ........................ ,  {'name': 'MissingReferenceError', 'message': 'Missing reference to handle creation'},  {'name': 'MissingReferenceError', 'message': 'Missing reference to handle creation'}]
```

That same log entry also had
```
Connector successfully run, storing last_run as 1673089379
```

**OpenCTI Docker Configuration**

```yaml
opencti:
    image: opencti/platform:5.5.1
    environment:
      - NODE_OPTIONS=--max-old-space-size=${MAX_OLD_SPACE_SIZE}
      - APP__PORT=8080
      - APP__BASE_URL=${OPENCTI_BASE_URL}
      - APP__SESSION_TIMEOUT=${SESSION_TIMEOUT}
      - APP__ADMIN__EMAIL=${OPENCTI_ADMIN_EMAIL}
      - APP__ADMIN__PASSWORD=${OPENCTI_ADMIN_PASSWORD}
      - APP__ADMIN__TOKEN=${OPENCTI_ADMIN_TOKEN}
      - APP__APP_LOGS__LOGS_LEVEL=error
      - SUBSCRIPTION_SCHEDULER__ENABLED=${SUBSCRIPTION_SCHEDULER_ENABLED}
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__URL=${ELASTICSEARCH_URL}
      - MINIO__ENDPOINT=minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO__SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - SMTP__HOSTNAME=${SMTP_HOSTNAME}
      - SMTP__USE_SSL=${SMTP_USE_SSL}
      - SMTP__REJECT_UNAUTHORIZED=${SMTP_REJECT_ANAUTHORIZED}
      - SMTP__PORT=${SMTP_PORT}
      - SMTP__USERNAME=${SMTP_USERNAME}
      - SMTP__PASSWORD=${SMTP_PASSWORD}
      - SMTP__FROM_EMAIL=${SMTP_FROM_EMAIL}
      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - minio
      - rabbitmq
    restart: always
```

**OpenCTI Datasets Connector Configuration**
```yaml
# OpenCTI Connector
  connector-opencti:
    image: opencti/connector-opencti:5.5.1
    environment:
      - OPENCTI_URL=${OPENCTI_URL}
      - OPENCTI_TOKEN=${CONN_OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONN_OPENCTI_TOKEN}
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=OpenCTI
      - CONNECTOR_SCOPE=marking-definition,identity,location
      - CONNECTOR_CONFIDENCE_LEVEL=50 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_RUN_AND_TERMINATE=false
      - CONNECTOR_LOG_LEVEL=info
      - CONFIG_SECTORS_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/sectors.json
      - CONFIG_GEOGRAPHY_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/geography.json
      - CONFIG_INTERVAL=7 # In days, must be strictly greater than 1
    restart: always
    depends_on:
      - opencti
```

## Screenshots (optional)

![connector](https://user-images.githubusercontent.com/121398311/211148647-64827f5a-239c-479b-8fd6-d6a2b2d47658.png)

![connector_sessions](https://user-images.githubusercontent.com/121398311/211148653-5d36c6cb-cdbe-4a58-857a-987887a7d3d2.png)

![connector_operations](https://user-images.githubusercontent.com/121398311/211148662-194a3bd5-de6f-441d-88e8-155e167ff6fc.png)

![connector_unicode_error](https://user-images.githubusercontent.com/121398311/211148688-30fdb1b3-8944-45d9-93aa-516bf95e34de.png)

![image](https://user-images.githubusercontent.com/121398311/211148775-09e65739-4852-45db-a8d7-bd8dbed70053.png)
![image](https://user-images.githubusercontent.com/121398311/211148957-ee0646be-a127-4fc8-aadb-5411bb4d2e8e.png)
![image](https://user-images.githubusercontent.com/121398311/211148861-7f3f613d-ab1d-47bc-960e-d5bd85c36e16.png)
