### ISSUE TITLE
[MITRE] Mitre connector fails to create "The MITRE Corporation" entity with default connector permissions

### ISSUE THREAD

**Issue by GraemeMeyerGT** [LuatixHQ/opencti#3037]
## Description

The MITRE connector (connector-mitre) seems to be failing to create the "The MITRE Corporation" entity (organization) when given the default connector permissions

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. } Docker on Ubuntu
2. OpenCTI version: { e.g. OpenCTI 1.0.2 } 5.5.4
3. OpenCTI client: { e.g. frontend or python } python? this is a connector

## Reproducible Steps

Steps to create the smallest reproducible scenario:
* Clean OpenCTI instance deployed with Docker
* Create user for mitre connector, give it the default "connector" role, and assign it to the platform org
* Bring up the mitre connector with the created user's token, and a unique uuid4 from [uuidgenerator.net](https://www.uuidgenerator.net/version4)

## Expected Output

I think the connector is supposed to create an org entity called "The MITRE Corporation", or update it if it already exists, and then create all the subsequent indicators/entities and attach them to that org entity. 

## Actual Output

Message: `{'name': 'ForbiddenAccess', 'message': 'You are not allowed to do this.'}`
Source: `{"type": "bundle", "id": "bundle--19413d5e-67e5-4a48-a4c8-afb06b7954de", "spec_version": "2.1", "x_opencti_seq": 2, "objects": [{"object_marking_refs": ["marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"], "id": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5", "type": "identity", "identity_class": "organization", "created": "2017-06-01T00:00:00.000Z", "modified": "2022-04-25T14:00:00.188Z", "name": "The MITRE Corporation", "spec_version": "2.1", "x_mitre_attack_spec_version": "2.1.0", "x_mitre_domains": ["enterprise-attack"], "x_mitre_version": "1.0", "nb_deps": 2}]}`

The connector continues to process work, but seemingly very slowly, and no entities created by the connector are visible in the platform. It seems likely to me that they are being created corrupt, with bad permissions or simply failing. They do not generate errors, only the one error for failure to create "The MITRE Corporation" is generated.

## Additional information

The docker compose service configuration for the MITRE connector (default, but with the token and connector_id replaced:

```yml
version: '3'
services:
  connector-mitre:
    image: opencti/connector-mitre:5.5.4
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${CONNECTOR_MITRE_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_MITRE_ID}
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - "CONNECTOR_NAME=MITRE Datasets"
      - CONNECTOR_SCOPE=marking-definition,identity,attack-pattern,course-of-action,intrusion-set,campaign,malware,tool,report,external-reference-as-report
      - CONNECTOR_CONFIDENCE_LEVEL=75 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_RUN_AND_TERMINATE=false
      - CONNECTOR_LOG_LEVEL=debug
      - MITRE_ENTERPRISE_FILE_URL=https://raw.githubusercontent.com/mitre-attack/attack-stix-data/master/enterprise-attack/enterprise-attack.json
      - MITRE_MOBILE_ATTACK_FILE_URL=https://raw.githubusercontent.com/mitre-attack/attack-stix-data/master/mobile-attack/mobile-attack.json
      - MITRE_ICS_ATTACK_FILE_URL=https://raw.githubusercontent.com/mitre-attack/attack-stix-data/master/ics-attack/ics-attack.json
      - MITRE_CAPEC_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/capec/2.1/stix-capec.json
      - MITRE_INTERVAL=7 # In days, must be strictly greater than 1
```

## Screenshots (optional)

The connector status after ~10 minutes of work:
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/107847353/224024913-13565833-4415-4814-af5a-208a93604861.png">

No entities are created by the connector after ~10 minutes:
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/107847353/224025030-2bba30ba-bbed-4bba-aa04-d6db39d9971e.png">

The default permissions assigned to the connector role:
<img width="688" alt="image" src="https://user-images.githubusercontent.com/107847353/224025331-3659f8a3-4a55-4a46-bb78-e70951e2bfb7.png">

**Comment by GraemeMeyerGT** [comment]
Chatted a little with @SamuelHassine on [Slack](https://filigran-community.slack.com/archives/CHZC2D38C/p1678365580974089), but wasn't able to solve this.

Have tried:
* Updating to 5.6.1
* Deleting the connector and it's RabbitMQ queue
* Verifying that the Platform Organization and the connector-mitre user are the same
* Deleting the connector and re-creating from scratch

No success.

As discussed with Sammuel, I also haven't modified any of the markings, or adjusted the Connector Role's permissions. 

In my latest deployment, I still get the same immediate error, the connector then goes on to seemingly happily process events (if extremely slowly), but no events or entities of any kind are ever created/visible.

After ~ an hour, the connector had processed ~2300 operations, but nothing was visible in the platform:

![image](https://user-images.githubusercontent.com/107847353/224075495-8b486dda-9707-42a2-8c60-5049c954682f.png)
![image](https://user-images.githubusercontent.com/107847353/224075535-3427e7e5-7846-4ae6-914c-4c17671c4f49.png)

**Comment by GraemeMeyerGT** [comment]
I've just tried adding the CVE connector (connector-cve) with the same methodology and permissions, and it seems to work fine in comparison.

**Comment by GraemeMeyerGT** [comment]
I am possibly having the same issue with the connector-disarm-framework connector:

```yml
  connector-disarm-framework:
    image: opencti/connector-disarm-framework:5.6.1
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${CONNECTOR_DISARM_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_DISARM_ID}
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - "CONNECTOR_NAME=DISARM Framework"
      - CONNECTOR_SCOPE=marking-definition,identity,attack-pattern,course-of-action,intrusion-set,campaign,malware,tool,report,narrative,event,channel
      - CONNECTOR_CONFIDENCE_LEVEL=75 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_RUN_AND_TERMINATE=false
      - CONNECTOR_LOG_LEVEL=info
      - DISARM_FRAMEWORK_URL=https://raw.githubusercontent.com/DISARMFoundation/DISARMframeworks/main/generated_files/DISARM_STIX/DISARM.json
      - DISARM_FRAMEWORK_INTERVAL=7 # In days, must be strictly greater than 1
```

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/107847353/224085638-70477cba-1116-4858-a64a-80aa35608a7b.png">

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/107847353/224085717-21f6a9ba-0424-4f64-8980-afe827bf3d53.png">

I have again verified:
* Connector user has same org as platform org
* Connector role granted

One interesting observation - all my connectors have multiple "sessions" open, some of which have been open longer than the system has been up (due to platform restarts during debugging):

<img width="258" alt="image" src="https://user-images.githubusercontent.com/107847353/224086196-b75148d9-ec11-496b-b1ee-e8b03c74a616.png">
