### ISSUE TITLE
custom map server

### ISSUE THREAD

**Issue by jack-reso** [LuatixHQ/opencti#3356]
## Prerequisites

- [ ] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [ ] I went through old GitHub issues and couldn't find anything relevant
- [ ] I googled the issue and didn't find anything relevant

## Environment

1. docker
2. opencti 5.7.4 docker
3. OpenCTI client: { e.g. frontend or python }

## Additional information
docker-compose file

```
 opencti:
    image: opencti/platform:5.7.4
    environment:
      - NODE_OPTIONS=--max-old-space-size=8096
      - APP__PORT=8080
      - APP__BASE_URL=${OPENCTI_BASE_URL}
      - APP__ADMIN__EMAIL=${OPENCTI_ADMIN_EMAIL}
      - APP__ADMIN__PASSWORD=${OPENCTI_ADMIN_PASSWORD}
      - .....
      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
      - APP__MAP__TILE__SERVER_DARK=http://xxx/{z}/{x}/{y}.png
      - APP__MAP__TILE__SERVER_LIGHT=http://xxx/{z}/{x}/{y}.png
   ```
APP__MAP__TILE__SERVER_DARK and APP__MAP__TILE__SERVER_LIGHT was add,and http://xxx/{z}/{x}/{y}.png is my own openstreetmap server.

when i start ,platform is start normol,but can't load map

i wonder know why?
