### ISSUE TITLE
Border style table doesn't work.

### ISSUE THREAD

**Issue by MrCl0wnLab** [LuatixHQ/opencti#3924]
## Use case
The html _border tag_ nowadays only works in preview mode, but inside the description, note it doesn't work.

> It would be interesting for the _thead tag_ to have a background to differentiate it from the other rows in the table.

## Nowadays
```markdown
| COL1 | COL2 | COL3 | 
| ---- | ----- |----- |
| google.com| GOOGLE | Information 01 | 
| bing.com/index.php?id=11111111111111111111111111111| BING| Information 02 | 
| teste.com| TESTE | Information 03 |
```

![table-Captura de tela de 2023-08-04 02-21-59](https://github.com/OpenCTI-Platform/opencti/assets/17049332/70aabae8-792a-4ac2-b9e0-cdcd31f44f11)

## Applied style
```css
th, td {
	border: 1px solid #CACACA;
	padding: 8px;
    text-align: left;
}
th, thead{
    vertical-align: middle;
    border-spacing: 4px;
}
thead{
    background-color:#fff;
    color:#333;
    font-weight: bold;
}
table {
    width: 100%;
    border-collapse: collapse;
    margin: 25px 0;
    font-size: 0.9em;
    font-family: sans-serif;
    min-width: 400px;
    box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
}
```

![table-style-Captura de tela de 2023-08-04 02-57-45](https://github.com/OpenCTI-Platform/opencti/assets/17049332/a72ccbc5-15e2-4b39-827b-5e87c6359d5a)
