### ISSUE TITLE
OpenIDConnectStrategy ERROR for user with more than 15 groups 

### ISSUE THREAD

**Issue by Tonnulus** [LuatixHQ/opencti#4924]
## Description

Users belonging to more than 15 groups that try to connect to OpenCTI with  `OpenIDConnectStrategy`  are redirected to the same login page with the Cookie opencti_flash : Invalid%20authentication%2C%20please%20ask%20your%20administrator without error on the browser.
On OpenCTI node logs (with info and debug mode) : 

{"category":"APP","level":"error","message":"Error login through provider oic","timestamp":"2023-11-07T09:38:17.710Z","version":"5.11.12"}

## Environment

1. OpenCTI 5.11.12 On Debian with docker
2. Keycloak 18.0.2
3.Client : Chrome, Firefox 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Configure OpenIDConnectStrategy
2. Create a user who can connect to OpenCTI
3. Add user in 15 groups
4. This same user will no longer be able to log in unless you remove some groups 

## Expected Output

Login

## Actual Output

![image](https://github.com/OpenCTI-Platform/opencti/assets/9503671/a97bfa81-fdef-4619-a51c-d551e255f41a)

## Additional information

Logs are needed to effectively debug this type of problem. 

```yaml
  PROVIDERS__LOCAL__STRATEGY: LocalStrategy
  PROVIDERS__OPENID__STRATEGY: OpenIDConnectStrategy
  PROVIDERS__OPENID__CONFIG__LABEL: "Login with Keycloak"
  PROVIDERS__OPENID__CONFIG__ISSUER: https://auth.lan.com/auth/realms/main
  PROVIDERS__OPENID__CONFIG__CLIENT_ID: oidc-opencti-prd
  PROVIDERS__OPENID__CONFIG__CLIENT_SECRET: ${OPENCTI_OPENID_CLIENT_SECRET}
  PROVIDERS__OPENID__CONFIG__REDIRECT_URIS: '["https://opencti/auth/oic/callback"]'
  PROVIDERS__OPENID__CONFIG__AUTO_CREATE_GROUP: "true"
  PROVIDERS__OPENID__CONFIG__GROUPS_MANAGEMENT__GROUPS_MAPPING: '[XXX]'
  PROVIDERS__OPENID__CONFIG__ROLES_SCOPE: opencti
  PROVIDERS__OPENID__CONFIG__GROUPS_SCOPE: opencti
```
