### ISSUE TITLE
To solve error type "DATABASE_ERROR: Fail to execute engine pagination" and "DATABASE_ERROR: Find direct ids fail"

### ISSUE THREAD

**Issue by Aster-Lin** [LuatixHQ/opencti#5666]
## Description

When searching for data using OpenCTIApiClient, it returns a database error. 
Details in the OpenCTI/platform's log indicate: 
```
search_phase_execution_exception caused by es_rejected_execution_exception: 
rejected execution of TimedRunnable{original=ActionRunnable#wrap[org.elasticsearch.search.SearchService$$Lambda/0x00007f2a191c3958@238b67b9], creationTimeNanos=66340965157418, startTimeNanos=0, finishTimeNanos=-1, failedOrRejected=false} 
on TaskExecutionTimeTrackingEsThreadPoolExecutor
[name = b29c005b33c8/search, queue capacity = 1000, task execution EWMA = 5.2ms, total task execution time = 51.3s, 
org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor@53dd29e0
[Running, pool size = 13, active threads = 13, queued tasks = 1000, completed tasks = 28269]]
```

The issue stems from a leak in the thread pool size in elasticsearch. 
To resolve this problem, it is essential to add thread pool configuration values in the Docker Compose file.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 22 / Docker
2. OpenCTI version: OpenCTI 5.12.18
3. OpenCTI client: pycti 5.12.18
4. Other environment details: portainer.io 2.11.1, elasticsearch 8.11.4

## Solution

Add thread_pool settings in elasticsearch environment.
`thread_pool.(search/get/write).queue_size=10000`
`thread_pool.(search/get/write).size=30`

In my case, I only need to set the search part in the thread pool. 
Therefore, my environment is as follows:

```
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.4
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      # Comment-out the line below for a cluster of multiple nodes
      - discovery.type=single-node
      # Uncomment the line below below for a cluster of multiple nodes
      # - cluster.name=docker-cluster
      - xpack.ml.enabled=false
      - xpack.security.enabled=false
      - thread_pool.search.queue_size=10000  # add queue_size (default 1000)
      - thread_pool.search.size=30  # add size (default 13)
      - "ES_JAVA_OPTS=-Xms${ELASTIC_MEMORY_SIZE} -Xmx${ELASTIC_MEMORY_SIZE}"
```

## Reference
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-threadpool.html
