### ISSUE TITLE
Struggling with configuration of the notifiers

### ISSUE THREAD

**Issue by febrezo** [LuatixHQ/opencti#6493]
## Prerequisites

- [x] I read the [Deployment and Setup](https://docs.opencti.io/latest/deployment/overview) section of the OpenCTI documentation as well as the [Troubleshooting](https://docs.opencti.io/latest/deployment/troubleshooting) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

I'm trying to configure the notification manager. Our current deployment is deploying OpenCTI 6.0.7 using standard configuration:

```
opencti:
    image: opencti/platform:6.0.7
    environment:
      - NODE_OPTIONS=--max-old-space-size=8096
      - APP__PORT=8080
      - APP__BASE_URL=${OPENCTI_BASE_URL}
      - APP__ADMIN__EMAIL=${OPENCTI_ADMIN_EMAIL}
      - APP__ADMIN__PASSWORD=${OPENCTI_ADMIN_PASSWORD}
      - APP__ADMIN__TOKEN=${OPENCTI_ADMIN_TOKEN}
      - APP__APP_LOGS__LOGS_LEVEL=error
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__URL=http://elasticsearch:9200
      - MINIO__ENDPOINT=minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO__SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - SMTP__HOSTNAME=${SMTP_HOST}
      - SMTP__PORT=${SMTP_PORT}
      - SMTP__USERNAME=${EMAIL_USERNAME}
      - SMTP__PASSWORD=${EMAIL_PASSWORD}
      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
      - NOTIFICATION_MANAGER__ENABLED=${NOTIFICATION_MANAGER__ENABLED}
    ports:
      - "18080:8080"
    depends_on:
      - redis
      - elasticsearch
      - minio
      - rabbitmq
    restart: always
  
  worker:
    image: opencti/worker:6.0.7
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - WORKER_LOG_LEVEL=info
    depends_on:
      - opencti
    deploy:
      mode: replicated
      replicas: ${OPENCTI_WORKERS}
    restart: always
```
    
By reading the [docs]() about notifiers, the default value is expected to make configurations work:
    
```
notification_manager:enabled 	NOTIFICATION_MANAGER__ENABLED 	true 	Enable/disable the notification manager
notification_manager:lock_key 	NOTIFICATION_MANAGER__LOCK_KEY 	notification_manager_lock 	Lock key for the manager in Redis
notification_manager:interval 	NOTIFICATION_MANAGER__INTERVAL 	10000 	Sender email address
```

This is confirmed in the Settings > Parameter  screen.

Not sure about how to diagnose the issue since no apparent log is seen in the OpenCTI container linked to notifications or in the workers. Need assistance to try to identify:

1) How to get more information about the notification system and what to search in the logs
2) How to  solve the issue.

## Environment

1. OS (where OpenCTI server runs): OpenCTI 6.0.7
2. OpenCTI version: OpenCTI 6.0.7
3. OpenCTI client: frontend
4. Other environment details:
![imagen](https://github.com/OpenCTI-Platform/opencti/assets/1590496/d1aacb2c-bfbf-44ff-b6e8-b7b625419ab2)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click on any instance and press the bell
2. Configure the User Interface Mailer (or any other notifier)
3. With that user (or with any other) add a new relationship (victimology, attribution, etc.)
4. Nothing happens... No notification appears.

## Additional information

N/A
