### ISSUE TITLE
LDAP invalid credentials 

### ISSUE THREAD

**Issue by vanitasKE** [LuatixHQ/opencti#8147]
## Description

Hello,

I have problem with configuration of LDAP and opencti got always invalid credentials even if they working from different enviroment so they are known.
Firewall is open also.
Any suggestions?
Thanks

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Additional information

```
This is my yaml file:
  opencti:
    image: opencti/platform:6.2.0
    environment:
      - NODE_OPTIONS=--max-old-space-size=8096
      - APP__PORT=8080
      - APP__BASE_URL=${OPENCTI_BASE_URL}
      - APP__ADMIN__EMAIL=${OPENCTI_ADMIN_EMAIL}
      - APP__ADMIN__PASSWORD=${OPENCTI_ADMIN_PASSWORD}
      - APP__ADMIN__TOKEN=${OPENCTI_ADMIN_TOKEN}
      - APP__APP_LOGS__LOGS_LEVEL=error
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__URL=http://elasticsearch:9200
      - MINIO__ENDPOINT=minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO__SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - SMTP__HOSTNAME=${SMTP_HOSTNAME}
      - SMTP__PORT=25
      - PROVIDERS__LDAP__STRATEGY=LdapStrategy
      - PROVIDERS__LDAP__CONFIG__URL=ldaps://example:636
      - PROVIDERS__LDAP__CONFIG__BIND_DN=CN=USERNAME,OU=System accounts,OU=xxx,OU=xxx,DC=xxx,DC=xxx>
      - PROVIDERS__LDAP__CONFIG__BIND_CREDENTIALS=XXX
      - PROVIDERS__LDAP__CONFIG__SEARCH_BASE=DC=xxx,DC=xxx
      - PROVIDERS__LDAP__CONFIG__SEARCH_FILTER=(sAMAccountName={{username}})
      - PROVIDERS__LDAP__CONFIG__MAIL_ATTRIBUTE=mail
      - PROVIDERS__LDAP__CONFIG__ALLOW_SELF_SIGNED=true
      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
	  - APP__LOGS_LEVEL=debug
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - elasticsearch
      - minio
      - rabbitmq
    restart: always
```

And this is error from lgos:

`
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":401},"message":"Bad login or password","name":"AUTH_FAILURE","stack":"AUTH_FAILURE: Bad login or password\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at AuthenticationFailure (/opt/opencti/build/src/config/errors.js:12:56)\n    at Object.token (/opt/opencti/build/src/resolvers/user.js:177:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}],"inner_relation_creation":0,"level":"error","message":"Bad login or password","operation":"Unspecified","query_attributes":[[{"arguments":[[{"is_empty":true,"name":"input","type":"Variable"}]],"name":"token"}]],"size":61,"source":"backend","time":34,"timestamp":"2024-08-22T19:28:42.712Z","type":"WRITE_ERROR","version":"6.2.0"}`

`{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":401},"message":"Bad login or password","name":"AUTH_FAILURE","stack":"AUTH_FAILURE: Bad login or password\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at AuthenticationFailure (/opt/opencti/build/src/config/errors.js:12:56)\n    at Object.token (/opt/opencti/build/src/resolvers/user.js:177:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}],"inner_relation_creation":0,"level":"error","message":"Bad login or password","operation":"Unspecified","query_attributes":[[{"arguments":[[{"is_empty":true,"name":"input","type":"Variable"}]],"name":"token"}]],"size":66,"source":"backend","time":24,"timestamp":"2024-08-22T19:29:00.391Z","type":"WRITE_ERROR","version":"6.2.0"}`
