### ISSUE TITLE
Platform 100% CPU Usage, unresponsive.

### ISSUE THREAD

**Issue by simonbjorzen-ts** [LuatixHQ/opencti#8833]
## Description

Platform containers reach 100% CPU usage and become unresponsive.
Causes liveness probe to fail and restarts.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.04 LTS (RKE2 K8S)
2. OpenCTI version: 6.3.7
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Start platform
2. Wait a couple of minutes
3. Some platform containers reach 100% CPU usage and stop responding
4. Health probe fails and restarts containers
5. Repeat

## Expected Output

Containers continue working and are not restarted

## Actual Output

Containers sit at 100% CPU utilization and do not respond to health probes.
Causing repeated restarts (hundreds per day)

## Additional information

Liveness probe configuration, tried increasing timeout but does not work.
```yaml
livenessProbe:
  httpGet:
    path: "/health?health_access_key=redacted"
    port: 8080
  failureThreshold: 3
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
```

No errors in log, final log message is usually an inference similar to this: 
```
{"category":"APP","id":"redacted uuid","level":"info","message":"Upsert inferred relation","relation":{"i_inference_weight":1,"i_rule_location_location":[{"data": redacted},"source":"backend","timestamp":"2024-10-30T14:08:17.918Z","version":"6.3.7"}
```

Could it be that the rules engine is overloading the system with inferences?
