### ISSUE TITLE
I want to import custom IoC to my opencti but issue is OPEN CTI API not reachable

### ISSUE THREAD

**Issue by thanh1am** [LuatixHQ/opencti#9564]
# ValueError: OpenCTI API is not reachable when importing STIX2 bundle in Docker Compose environment

## Description

I am encountering an issue when attempting to import a STIX2 bundle using the OpenCTI Python SDK in a Docker Compose setup. The Python script fails with the following error:

---
1. `docker-compose.yml` file
   ```yaml
   import-service:
     image: python:3.9
     volumes:
       - ./import.py:/usr/src/app/import.py
       - ./test.json:/usr/src/app/test.json
       - ./requirements.txt:/usr/src/app/requirements.txt
     environment:
       - OPENCTI_API_URL=http://opencti:1024
       - OPENCTI_API_TOKEN=${OPENCTI_ADMIN_TOKEN}
       - CONNECTOR_ID=62140cad-e0a1-40e5-897b-d9e328d4a187
     command: ["sh", "-c", "pip install -r /usr/src/app/requirements.txt && python /usr/src/app/import.py"]
     depends_on:
       - opencti
     restart: always
2. Python script for importing:
```
import os
from pycti import OpenCTIApiClient

# Load OpenCTI URL and token from environment variables
api_url = os.getenv('OPENCTI_API_URL')
api_token = os.getenv('OPENCTI_API_TOKEN')

# OpenCTI initialization
opencti_api_client = OpenCTIApiClient(api_url, api_token)

# File to import
file_to_import = "./test.json"

# Import the bundle
opencti_api_client.stix2.import_bundle_from_file(file_to_import, True)
```

Any solve for this????
