### ISSUE TITLE
Failed to establish a new connection: [Errno 111] Connection refused / OpenCTI

### ISSUE THREAD

**Issue by ThierryIT** [LuatixHQ/opencti#9716]
## Description

`requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a12401a4d40>: Failed to establish a new connection: [Errno 111] Connection refused')) taskName=null`

Terminated

## Environment

1. OS Ubuntu 24.04.1 LTS
2. OpenCTI 6.4.8

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. restart stack OpenCTI in Portainer

## Expected Output

working without any error messages ?

## Actual Output

`requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a12401a4d40>: Failed to establish a new connection: [Errno 111] Connection refused')) taskName=null`

Terminated

## Additional information

I have commanted all my connector except one: IPINFO for testing purpose ... 
All the connector previously used have this pb.

## Screenshots (optional)
```
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7423fa2abc80>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py", line 409, in health_check
    test = self.query(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py", line 340, in query
    r = self.session.post(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7423fa2abc80>: Failed to establish a new connection: [Errno 111] Connection refused')) taskName=null
Terminated
```

My compose file:
```

  services:
  redis:
    image: redis:7.4.1
    restart: always
    command: ["redis-server", "--appendonly", "yes", "--maxmemory", "12000mb", "--maxmemory-policy", "volatile-lru"]
    #command: ["redis-server", "--appendonly", "yes", "--appendfsync", "always", "--maxmemory", "32000mb", "--maxmemory-policy", "allkeys-lru"]
    #command:
    #- bash
    #- -c
    #- redis-server --maxmemory 26000mb --maxmemory-policy allkeys-lru #--client-output-buffer-limit "pubsub 128MB 64MB 60"
    #- redis-server --maxmemory-policy  allkeys-random #--client-output-buffer-limit "pubsub 128MB 64MB 60"
    #- redis-cli --config-set --client-output-buffer-limit "slave 836870912 836870912 0"  Actual client command syntax - recis-cli  then config set client-output-buffer-limit "slave 836870912 836870912 0"
    #command:
    #  - bash
    #  - -c
    #entrypoint: redis-server --appendonly yes --maxmemory 15000mb --maxmemory-policy allkeys-lru 
    #redis-server --appendonly no --maxmemory $$(( $$( cat /sys/fs/cgroup/memory/memory.limit_in_bytes 2>/dev/null || cat /sys/fs/cgroup/memory.max ) - 100000000)) --maxmemory-policy volatile-lru
    #deploy:
    #  resources:
    #    limits:
    #      memory: 16000M
    volumes:
      - redisdata:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      # Comment out the line below for single-node
      - discovery.type=single-node
      # Uncomment line below below for a cluster of multiple nodes
      # - cluster.name=docker-cluster
      - xpack.ml.enabled=false
      - xpack.security.enabled=false
      - thread_pool.search.queue_size=5000
      - logger.org.elasticsearch.discovery="ERROR"
      #- bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ELASTIC_MEMORY_SIZE} -Xmx${ELASTIC_MEMORY_SIZE}"
      #- "ES_JAVA_OPTS: -Xms6G -Xmx6G"  
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  minio:
    image: minio/minio:RELEASE.2025-01-20T14-49-07Z
    volumes:
      - s3data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data
  rabbitmq:
    image: rabbitmq:4.0.5-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_NODENAME=rabbit01@localhost
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - amqpdata:/var/lib/rabbitmq
    restart: always
  opencti:
    image: opencti/platform:6.4.8
    environment:
      - NODE_OPTIONS=--max-old-space-size=8096
      - APP__PORT=8080
      - APP__BASE_URL=${OPENCTI_BASE_URL}
      - APP__ADMIN__EMAIL=${OPENCTI_ADMIN_EMAIL}
      - APP__ADMIN__PASSWORD=${OPENCTI_ADMIN_PASSWORD}
      - APP__ADMIN__TOKEN=${OPENCTI_ADMIN_TOKEN}
      - APP__APP_LOGS__LOGS_LEVEL=error
     #- APP__BASE_PATH=/opencti
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__URL=http://elasticsearch:9200
      - ELASTICSEARCH__NUMBER_OF_REPLICAS=0
      - MINIO__ENDPOINT=minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO__SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - SMTP__HOSTNAME=localhost
      #- SMTP__PORT=25
      #- SMTP__USE_SSL=true
      #- SMTP__REJECT_UNAUTHORIZED=false
      #- SMTP__USER=
      #- SMTP__PASSWORD=
      #- SMTP__FROM_EMAIL=
      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
      - PROTECT_SENSITIVE_CONFIG__ENABLED=false
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - elasticsearch
      - minio
      - rabbitmq
    restart: always
  worker:
    image: opencti/worker:6.4.8
    environment:
      - OPENCTI_URL=http://localhost:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - WORKER_LOG_LEVEL=info
    depends_on:
      - opencti
    deploy:
      mode: replicated
      replicas: 3
    restart: always
  connector-opencti:
    image: opencti/connector-opencti:6.4.8
    environment:
      - OPENCTI_URL=http://localhost:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=8677408d-b800-4xxxxxxxxxx
      - "CONNECTOR_NAME=OpenCTI Datasets"
      - CONNECTOR_SCOPE=marking-definition,identity,location
      - CONNECTOR_CONFIDENCE_LEVEL=100
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_RUN_AND_TERMINATE=false
      - CONNECTOR_LOG_LEVEL=error
      - CONFIG_SECTORS_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/sectors.json
      - CONFIG_GEOGRAPHY_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/geography.json
      - CONFIG_COMPANIES_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/companies.json
      - CONFIG_REMOVE_CREATOR=false
      - CONFIG_INTERVAL=7 # In days
    restart: always
    depends_on:
      - opencti

  connector-ipinfo:
    image: opencti/connector-ipinfo:6.4.8
    environment:
      - OPENCTI_URL=http://localhost:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=323a96c4-1419-4xxxxxxxxxxx
      - CONNECTOR_NAME=IpInfo
      - CONNECTOR_SCOPE=IPv4-Addr, IPv6-Addr
      - CONNECTOR_AUTO=true
      - CONNECTOR_CONFIDENCE_LEVEL=75 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=error
      - IPINFO_TOKEN=IPINFOKEYHERE
      - IPINFO_MAX_TLP=TLP:AMBER
      - IPINFO_USE_ASN_NAME=true
    restart: always
    depends_on:
      - opencti
  

volumes:
  esdata:
  s3data:
  redisdata:
  amqpdata:

```
